name: QA Assignment Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Playwright dependencies
        uses: microsoft/playwright-github-action@v1

      - name: Install project dependencies
        run: npm install

      - name: Install Playwright
        run: npx playwright install

      - name: Start Python HTTP server
        run: |
          python -m http.server 8000 &
          sleep 10

      - name: Run tests
        run: npm run test
